import os 
from dotenv import load_dotenv

load_dotenv()

AZURE_STORAGE_CONTAINER_NAME = os.environ.get("STORAGE_CONTAINER_NAME")
AZURE_STORAGE_ACCOUNT_NAME = os.environ.get("STORAGE_ACCOUNT_NAME")
AZURE_STORAGE_ACCOUNT_KEY = os.environ.get("STORAGE_ACCOUNT_KEY")

AZURE_DOCUMENT_INTELLIGENCE_API_KEY = os.environ.get("DOCUMENT_INTELLIGENCE_API_KEY")
AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT = os.environ.get("DOCUMENT_INTELLIGENCE_ENDPOINT")

CHROMA_PATH = os.environ.get("CHROMA_PATH")

AZURE_COGNITIVE_SEARCH_SERVICE_NAME = os.environ.get("COGNITIVE_SEARCH_SERVICE_NAME")
AZURE_COGNITIVE_SEARCH_INDEX_NAME = os.environ.get("COGNITIVE_SEARCH_INDEX_NAME")
AZURE_COGNITIVE_SEARCH_API_KEY = os.environ.get("COGNITIVE_SEARCH_API_KEY")
AZURE_COGNITIVE_SEARCH_ENDPOINT = os.environ.get("COGNITIVE_SEARCH_ENDPOINT")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")